### ISSUE TITLE
作者 您好 opencore 版本问题

### ISSUE THREAD

**Issue by ZJUprince** [SummerEmber/Lenovo-ThinkCentre-M93p-Tiny#2]
我看您已经升级了0.6.0，但我引导后用Hackintool查看，发现是0.5.9，请问是怎么回事呢？

**Comment by zlylong** [comment]
> 我看您已经升级了0.6.0，但我引导后用Hackintool查看，发现是0.5.9，请问是怎么回事呢？

没有成功覆盖。
