### ISSUE TITLE
休眠后时间不正确问题

### ISSUE THREAD

**Issue by zlylong** [SummerEmber/Lenovo-ThinkCentre-M93p-Tiny#4]
Hi，作者你好，我的M93P现在是只要休眠，唤醒以后时间就是睡眠时间，需要手动去同步时间，请问这个是引导问题吗？我已经换过主板电池和短接清空COMS了。

**Comment by SummerEmber** [comment]
> Hi，作者你好，我的M93P现在是只要休眠，唤醒以后时间就是睡眠时间，需要手动去同步时间，请问这个是引导问题吗？我已经换过主板电池和短接清空COMS了。

我这没有遇到过这个问题，你是双系统吗？可以试一下分别用Clover和OC引导是不是都有这个问题。

**Comment by zlylong** [comment]
> > Hi，作者你好，我的M93P现在是只要休眠，唤醒以后时间就是睡眠时间，需要手动去同步时间，请问这个是引导问题吗？我已经换过主板电池和短接清空COMS了。
> 
> 我这没有遇到过这个问题，你是双系统吗？可以试一下分别用Clover和OC引导是不是都有这个问题。

我是单系统，感谢回答，那么大概率是主板有问题了。
