### ISSUE TITLE
BCM94352HMB蓝牙问题

### ISSUE THREAD

**Issue by zlylong** [SummerEmber/Lenovo-ThinkCentre-M93p-Tiny#5]
我使用的是opencore引导，BCM94352HMB蓝牙基本处于不能使用状态。请问换clover会好一点吗？

**Comment by SummerEmber** [comment]
94352HMB的蓝牙确实会有问题，与引导方式无关。我这有些蓝牙音响可以连得上，鼠标基本不行。

**Comment by zlylong** [comment]
好的，谢谢。

**Comment by zlylong** [comment]
> 94352HMB的蓝牙确实会有问题，与引导方式无关。我这有些蓝牙音响可以连得上，鼠标基本不行。

更新了驱动和opencore6.1以后蓝牙就能用了。。。
